training:
  batch_size: 16
  n_epochs: 500000
  n_iters: 150001
  snapshot_freq: 5000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false

sampling:
  source_path: '/data/liaohx/Cine_Super_Resolution/new_dataset.npy'
  batch_size: 200
  data_init: false
  step_lr: 0.0000018
  n_steps_each: 2  # corrector 步数
  ckpt_id:
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 10

fast_fid:
  batch_size: 1000
  num_samples: 1000
  step_lr: 0.0000018
  n_steps_each: 3
  begin_ckpt: 100000
  end_ckpt: 150000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 5000
  end_ckpt: 150000
  batch_size: 100

data:
  dataset: "CINE"
  category: "tower"
  image_size: 128
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: true     
  num_workers: 32
  training_dataset_path: /data/liaohx/Cine_Super_Resolution/Data/Non_Hamming/processed_data/training_set.npy  # the path of dataset
  testing_dataset_path: /data/liaohx/Cine_Super_Resolution/new_dataset.npy  # the path of dataset

model:
  in_channels: 2
  out_channels: 1
  sigma_begin: 196
  num_classes: 300  #设置扩散进程步数
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  
  # python main.py --config cine.yml  --exp ./outlogs --doc cinesr --resume_training
  # python main.py --config cine.yml  --exp ./outlogs --doc cinesr --sample --i cine_samples_1215
  # python main.py --config cine.yml  --exp /data/liaohx/Cine_Super_Resolution/Experiment_results/NCSNv2/Non_Hamming --doc non_hamming