data:
    dataset: "CINE"
    image_size: 128  # the resolution of images
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 2
    training_dataset_path: /data/liaohx/Cine_Super_Resolution/ProcessedData/ACDC/Processed/training_dataset.npy
    testing_dataset_path: /data/liaohx/Cine_Super_Resolution/ProcessedData/ACDC/Processed/testing_dataset.npy

training:
    batch_size: 1
    n_epochs: 10000
    n_iters: 500000
    snapshot_freq: 5000
    validation_freq: 2500

sampling:
    batch_size: 4
    last_only: True
    sampling_path : ""  # source_image
    shot: 50

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001

loss:
    lambda_gp: 10