data:
    dataset: "CINE"
    image_size: 128
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 2
    training_dataset_path: /data/liaohx/Cine_Super_Resolution/ProcessedData/ACDC/Processed/training_dataset.npy
    testing_dataset_path: /data/liaohx/Cine_Super_Resolution/ProcessedData/ACDC/Processed/testing_dataset.npy

model:
    type: "simple"
    in_channels: 2
    out_ch: 1
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 1
    n_epochs: 10000
    n_iters: 500000
    snapshot_freq: 5000
    validation_freq: 2500

sampling:
    shot: 50
    batch_size: 4
    last_only: True
    ckpt_id:
    sampling_path : 
    num_measurement : 4

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001